//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyApplication.DBModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WLBSurveyEntities : DbContext
    {
        public WLBSurveyEntities()
            : base("name=WLBSurveyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mstOption> mstOptions { get; set; }
        public virtual DbSet<mstQuestion> mstQuestions { get; set; }
        public virtual DbSet<mstUser> mstUsers { get; set; }
        public virtual DbSet<SurveyHeader> SurveyHeaders { get; set; }
        public virtual DbSet<SurveyDetail> SurveyDetails { get; set; }
    }
}
