//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyApplication.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyHeader()
        {
            this.SurveyDetails = new HashSet<SurveyDetail>();
        }
    
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public string Division { get; set; }
        public string DesigCode { get; set; }
        public string DesigName { get; set; }
        public string ServeyScore { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Suggetions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyDetail> SurveyDetails { get; set; }
    }
}
