//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyApplication.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyDetail
    {
        public int Id { get; set; }
        public Nullable<int> ServeyHeaderId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string Question { get; set; }
        public Nullable<int> SelectedOptionId { get; set; }
        public string SelectedOptionName { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual SurveyHeader SurveyHeader { get; set; }
    }
}
